### ISSUE TITLE
`Could not find artifact org.openjump:OpenJUMP:jar:2.2.0-main-SNAPSHOT`

### ISSUE THREAD

**Issue by micycle1** [openjump-gis/topology-extension#3]
org.openjump:OpenJUMP:jar:2.2.0 has disappeared from https://ojrepo.soldin.de/org/openjump/OpenJUMP/

**Comment by edeso** [comment]
right, please use the snapshot jars that are updated when snapshots are build
```xml
    <dependency>
      <groupId>org.openjump</groupId>
      <artifactId>OpenJUMP</artifactId>
      <version>main-SNAPSHOT</version>
    </dependency>
```

the release version mvn jars were incomplete before and we want to encourage to develop against the latest version anyway.

**Comment by micycle1** [comment]
Ok, can you update the pom.xml of this project then? It's pointed to 2.2.0-main-SNAPSHOT.

**Comment by edeso** [comment]
that's probably true for most of the extensions. will go over them when time permits. feel free to raise a PR though. that can be merged quickly. thanks!

**Comment by micycle1** [comment]
I would but there's the issue of whether you want/need to bump the version.

**Comment by edeso** [comment]
sorry, what issue? can you provide more details?

**Comment by micycle1** [comment]
Whether bumping the version warrants an version upgrade from 2.0.6.

**Comment by edeso** [comment]
as these extensions are bundled with OJ releases anyway we do not keep additional compatibility versioning. the general extension/plugin and major API are supposed to be stable unless the OJ major version changes, as it did with OJ2.

but sure,  there may be OJ dependency upgrades which force extensions to follow lead. if they are detected, they will be treated as OJ issue and fixed by updating the extension and include the fixed version.

so, no version bump for the extension needed. go ahead.
